    # See https://pre-commit.com for more information
    # See https://pre-commit.com/hooks.html for more hooks
    repos:
      - repo: https://github.com/ambv/black
        rev: 24.4.2
        hooks:
          - id: black
            language_version: python3.12
      -   repo: https://github.com/PyCQA/flake8
          rev: 7.1.0
          hooks:
          - id: flake8
            language_version: python3.12
      -   repo: https://github.com/pre-commit/mirrors-mypy
          rev: 'v1.10.0'  # Use the sha / tag you want to point at
          hooks:
          -   id: mypy
              language_version: python3.12
              additional_dependencies: [types-PyYAML==6.0.12.*]