# See https://pre-commit.com for more information
fail_fast: false
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.

    rev: 0.8.13
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.

    rev: 0.8.13
    hooks:
      - id: uv-export
  - repo: https://github.com/ambv/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.12
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        language_version: python3.12
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: uv run python -m pylint
        language: system
        types: [python]
        args: ["--fail-under", "9.5"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.17.1' # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        language_version: python3.12
        additional_dependencies: [types-PyYAML==6.0.12.*]
  - repo: https://github.com/google/yamlfmt
    rev: v0.17.2
    hooks:
      - id: yamlfmt
