version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: '[%(levelname)-8s|%(pathname)s|L%(lineno)d] %(asctime)s:%(message)s'
    datefmt: '%Y-%m-%dT%H:%M:%S%z'
  extended:
    format: '[%(levelname)-8s|p%(process)s|%(pathname)s|L%(lineno)d] %(asctime)s:%(message)s'
    datefmt: '%Y-%m-%dT%H:%M:%S%z'
handlers:
  stdout:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  queue_handler:
    class: logging.handlers.QueueHandler
    handlers:
    - stdout
    respect_handler_level: true
loggers:
  root:
    level: DEBUG
    handlers:
    - queue_handler